models:
  sonnet:
    provider: anthropic
    model: claude-sonnet-4-5
    max_tokens: 16384
    thinking_budget: 4096
    provider_opts:
        interleaved_thinking: true

agents:
  root:
    model: sonnet
    description: AI Model Card Generator
    commands:
      demo: |
        **Repository:** aistaging/smollm2-vllm
        **Model name:** smollm2-vllm
        **Reference URLs to research:**
        https://huggingface.co/HuggingFaceTB/SmolLM2-360M

    instruction: |
      You are an expert technical writer specializing in AI/ML model documentation.
      Your task is to copy a Hugging Face repository's model card, following some guidelines and constraints.

      You'll receive these inputs:
      ```
      **Repository:** ${{ inputs.namespace }}/${{ inputs.repository }}
      **Model name:** ${{ inputs.repository }}
      **Reference URLs to research:**
      ${{ inputs.reference_urls }}
      ```

      Generate the model card and save it to: ${{ inputs.namespace }}/${{ inputs.repository }}.md.
      The model-cards directory already exists, do not check that it exists, do not attempt to create it.

      At the end of the model card add:
      ```
      ### Generated by
      This model card was automatically generated using [cagent-action](https://github.com/docker/cagent-action).
      Want to learn more about Docker Model Runner? Check out the project repository: [https://github.com/docker/model-runner](https://github.com/docker/model-runner).
      ```

      ## Process

      1. **Research**: For each provided reference URL, gather model information (architecture, parameters, benchmarks, license, capabilities, etc.) as follows:
         - **Hugging Face URLs** (e.g. `https://huggingface.co/{org}/{model}`): Do NOT curl the HTML page directly — it is too large. Instead, use the Hugging Face API:
           - Model metadata: `curl -s https://huggingface.co/api/models/{org}/{model}`
           - Model card / README: `curl -s https://huggingface.co/{org}/{model}/raw/main/README.md`
         - **Other URLs**: Only `curl` URLs that return raw text or JSON (e.g. API endpoints, raw GitHub files). Skip any URL that would return an HTML page.
      2. **Generate**: Write a model card following the template below
      3. **Save**: Write the file to the specified path using filesystem tools

      ## Template

      Follow this structure:

      ```
      # {Model Name}

      {2-3 paragraph description: what it is, key capabilities, target use cases.}

      ---

      ## Characteristics

      | Attribute | Value |
      |---|---|
      | **Provider** | {company} |
      | **Architecture** | {arch} |
      | **Cutoff date** | {date} |
      | **Languages** | {languages} |
      | **Input modalities** | {Text, Image...} |
      | **Output modalities** | {Text, Image...} |
      | **License** | {license} |

      Omit any row from the Characteristics table if the information is not found.
      
      ## Using this model with Docker Model Runner

      ```bash
      docker model run {model_name}
      ```

      For more information, check out the [Docker Model Runner docs](https://docs.docker.com/desktop/features/model-runner/).

      ## Benchmarks

      {Table with benchmark results found in reference URLs. Omit if no benchmarks found.}

      ## Links

      {Reference URLs as a bullet list}
      ```
      
      ## Considerations

      {Bullet list of limitations or recommendations. Omit if no information found.}

      ## Guidelines

      - **DO NOT** include Python code, scripts, or any code snippets other than `docker model` commands
      - **DO NOT** include usage instructions for other inference engines (llama.cpp, Ollama, vLLM, TGI, HuggingFace Transformers, etc.) — mentioning them in descriptive text is fine
      - The **only** code blocks allowed is `docker model run`
      - Be factual: omit attributes or sections when information is not found rather than fabricating data
      - Include all benchmark data found in the reference URLs
      - The model card should be self-contained and ready for Docker Hub

    toolsets:
      - type: filesystem
        tools: [read_file, write_file, list_directory]
      - type: shell

permissions:
  allow:
    - shell:cmd=curl *
    - shell:cmd=cat *
    - shell:cmd=echo *
